import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {ensureDependencies, nodeEnv, policyRoot, requireNode, run} from './runtime.mjs';

const repository = 'https://github.com/Mou652/commit-policy.git';
const config = `# Shared policy: https://github.com/Mou652/commit-policy\nremotes:\n  - git_url: ${repository}\n    ref: main\n    configs:\n      - lefthook.yml\n    refetch_frequency: always\n`;
const quote = value => `'${value.replaceAll("'", "'\\''")}'`;

try {
  requireNode();
  const requested = resolve(process.argv[2] || process.cwd());
  const target = run('git', ['rev-parse', '--show-toplevel'], {cwd: requested}).trim();
  const git = args => run('git', args, {cwd: target});
  const branch = git(['branch', '--show-current']);
  if (branch.trim() === 'test') throw new Error('请先切换开发分支，再添加接入配置');
  const customHooks = spawnSync('git', ['config', '--get', 'core.hooksPath'], {cwd: target, encoding: 'utf8'});
  if (customHooks.status === 0 && customHooks.stdout.trim()) throw new Error('已有 core.hooksPath；请先确认现有 Hook 的整合方案，本脚本不会覆盖');
  const gitPath = name => resolve(target, git(['rev-parse', '--git-path', name]).trim());
  const configFile = join(target, 'lefthook.yml');
  if (existsSync(configFile) && readFileSync(configFile, 'utf8') !== config) throw new Error('已有不同的 lefthook.yml；请整合配置后接入，本脚本不会覆盖');
  const localFile = join(target, 'lefthook-local.yml');
  if (existsSync(localFile) && !readFileSync(localFile, 'utf8').startsWith('# Generated by Mou652/commit-policy\n')) throw new Error('已有 lefthook-local.yml，本脚本不会覆盖');
  for (const hook of ['pre-commit', 'commit-msg']) {
    const file = gitPath(`hooks/${hook}`);
    if (existsSync(file) && !readFileSync(file, 'utf8').includes('LEFTHOOK')) throw new Error(`已有 ${hook} Hook，本脚本不会覆盖`);
  }
  const {lefthook} = ensureDependencies();
  const stateDir = gitPath('commit-policy');
  mkdirSync(stateDir, {recursive: true});
  const rc = join(stateDir, 'env.sh');
  writeFileSync(rc, `# Generated by Mou652/commit-policy\nexport PATH=${quote(dirname(process.execPath))}:"$PATH"\n`);
  writeFileSync(configFile, config);
  const binaryCommand = `${quote(process.execPath)} ${quote(lefthook)}`;
  writeFileSync(localFile, `# Generated by Mou652/commit-policy\nlefthook: ${JSON.stringify(binaryCommand)}\nrc: ${JSON.stringify(quote(rc))}\n`);
  const exclude = gitPath('info/exclude');
  mkdirSync(dirname(exclude), {recursive: true});
  const previous = existsSync(exclude) ? readFileSync(exclude, 'utf8') : '';
  if (!previous.split(/\r?\n/u).includes('/lefthook-local.yml')) writeFileSync(exclude, `${previous}${previous.endsWith('\n') || !previous ? '' : '\n'}/lefthook-local.yml\n`);
  run(process.execPath, [lefthook, 'install'], {cwd: target, stdio: 'inherit', env: nodeEnv});
  const effective = JSON.parse(run(process.execPath, [lefthook, 'dump', '--format', 'json'], {cwd: target}));
  const staged = effective['pre-commit']?.scripts?.['check-staged.sh'];
  const message = effective['commit-msg']?.scripts?.['check-message.sh'];
  if (!staged || !message) throw new Error('远程规则未加载完整，首次接入失败；请确认 GitHub 网络可用后重试');
  for (const hook of ['pre-commit', 'commit-msg']) if (!existsSync(gitPath(`hooks/${hook}`))) throw new Error(`缺少 ${hook} Hook`);
  writeFileSync(join(stateDir, 'installation.json'), JSON.stringify({repository, policyRoot, node: process.execPath}, null, 2) + '\n');
  console.log(`\n[commit-policy] 接入完成: ${target}\n只新增配置与本地 Hook；没有暂存、提交或推送业务项目。\n下一次执行 Hook 时自动刷新 GitHub 规则。`);
} catch (error) {
  console.error(`[commit-policy] 接入失败: ${error.message}`);
  process.exitCode = 1;
}
